version: '3.7'
services:
  web:
    container_name: threecommas-web
    image: reborngeek/lamp:latest
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/home/thehardylawfirm.com/
      - ./apache/sites-available/:/etc/apache2/sites-available/
      - ./apache/sites-available/:/etc/apache2/sites-enabled/
      - ./apache/ssl/:/etc/apache2/ssl/
    ports:
      - "80:80"
      - "443:443"
    stdin_open: true
    tty: true

volumes:
  dbdata: